### ISSUE TITLE
特殊shiro问题

### ISSUE THREAD

**Issue by Lufei101** [sma11new/Pyke-Shiro#1]
![image](https://github.com/sma11new/Pyke-Shiro/assets/93892809/77f43689-bab6-463b-9054-8bd5eb902190)
如图类似这样的，cookie里面需要带上另一个值才会被检测出shiro框架并且才可以利用，所以想提个小意见，可不可以在复杂请求中的cookie部分追加rememberMe而不是替换原有的cookie

**Comment by sma11new** [comment]
> ![image](https://private-user-images.githubusercontent.com/93892809/311407024-77f43689-bab6-463b-9054-8bd5eb902190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzM4MTEsIm5iZiI6MTcwOTk3MzUxMSwicGF0aCI6Ii85Mzg5MjgwOS8zMTE0MDcwMjQtNzdmNDM2ODktYmFiNi00NjNiLTkwNTQtOGJkNWViOTAyMTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA4MzgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MTBkNWE3MGI3N2U2OGYwYjZjZGY1MGU3YzQzODQ3ZGQwZGNmYjBiMGIyZThhNmQ5YzkwNDc2MGIxZTJiMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xmubF2i5UH11Xcpb30Rheqt0iWIc4eBnIW0x_BeU62Y) 如图类似这样的，cookie里面需要带上另一个值才会被检测出shiro框架并且才可以利用，所以想提个小意见，可不可以在复杂请求中的cookie部分追加rememberMe而不是替换原有的cookie

好的🫡 看起来是需要考虑这种情况

**Comment by sma11new** [comment]
> ![image](https://private-user-images.githubusercontent.com/93892809/311407024-77f43689-bab6-463b-9054-8bd5eb902190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTU1OTEsIm5iZiI6MTcxMDI5NTI5MSwicGF0aCI6Ii85Mzg5MjgwOS8zMTE0MDcwMjQtNzdmNDM2ODktYmFiNi00NjNiLTkwNTQtOGJkNWViOTAyMTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NDJmMDMzODg4YjM0NmJjZDQxYzBmMDA1NGUwZTAxYzllMjJkN2JmNmI3NmRjNzY5NTJmZTgwZDc1ZjI2OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LGFQd_MeaST5f_3Md39yQV1aLu_ytWtOYzGJnW-vzi8) 如图类似这样的，cookie里面需要带上另一个值才会被检测出shiro框架并且才可以利用，所以想提个小意见，可不可以在复杂请求中的cookie部分追加rememberMe而不是替换原有的cookie

0.3版本中已添加可选是否保留Cookie，欢迎继续使用提issues
